### ISSUE TITLE
Licence required

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/livestream-overlay#3]
It looks probable that this will be reused for SR.

@Tyler-Ward @mildlyincompetent  are you happy with MIT?

**Comment by Tyler-Ward** [comment]
MIT is fine with me @mildlyincompetent if you are happy with this as well i will get a licence added

**Comment by mildlyincompetent** [comment]
![](https://i.imgflip.com/2uldjl.jpg)

**Comment by Tyler-Ward** [comment]
fixed in 8532ea157e17b847febdbbd8547ccf72a97b7a8f.
